import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { v4 as uuidv4 } from 'uuid';

export interface Notification {
  id: string;
  type: 'success' | 'error' | 'warning' | 'info';
  title: string;
  message: string;
  timestamp: number;
  read: boolean;
  /** Link to navigate when clicking the notification */
  actionUrl?: string;
  /** Whether this was generated by the system (auto-detected) vs user action */
  origin?: 'user' | 'system';
}

interface NotificationState {
  notifications: Notification[];
  addNotification: (_notification: Omit<Notification, 'id' | 'timestamp' | 'read'>) => void;
  markAsRead: (_id: string) => void;
  markAllRead: () => void;
  clearAll: () => void;
  unreadCount: () => number;
}

const MAX_NOTIFICATIONS = 50;
const PERSIST_MAX = 20;

export const useNotificationStore = create<NotificationState>()(
  persist(
    (set, get) => ({
      notifications: [],

      addNotification: (notification) => {
        const newNotification: Notification = {
          ...notification,
          id: uuidv4(),
          timestamp: Date.now(),
          read: false,
          origin: notification.origin || 'user',
        };
        set((state) => {
          const updated = [newNotification, ...state.notifications];
          return { notifications: updated.slice(0, MAX_NOTIFICATIONS) };
        });
      },

      markAsRead: (id) => {
        set((state) => ({
          notifications: state.notifications.map((n) =>
            n.id === id ? { ...n, read: true } : n
          ),
        }));
      },

      markAllRead: () => {
        set((state) => ({
          notifications: state.notifications.map((n) => ({ ...n, read: true })),
        }));
      },

      clearAll: () => set({ notifications: [] }),

      unreadCount: () => get().notifications.filter((n) => !n.read).length,
    }),
    {
      name: 'agentteams-notifications',
      version: 1,
      partialize: (state) => ({
        // Only persist the most recent notifications
        notifications: state.notifications.slice(0, PERSIST_MAX),
      }),
    }
  )
);
