apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hiclaw-system

resources:
  - 10-pvc.yaml
  - 20-dashboard.yaml
  - 30-ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hiclaw
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
